### ISSUE TITLE
The All tag dance from one side to another when multiple instances are on the page

### ISSUE THREAD

**Issue by dej611** [lingz/alphabetical_paginate#25]
A picture is worth thousand words:
![screen shot 2014-10-19 at 15 47 46](https://cloud.githubusercontent.com/assets/924948/5057478/a4e9846c-6cba-11e4-8c6c-a696e7e7a122.png)

**Comment by sprosser** [comment]
I've had a PR up a couple weeks to address this, but it has not been merged 

https://github.com/lingz/alphabetical_paginate/pull/32

**Comment by lingz** [comment]
Merged and released with 2.3.0
