### ISSUE TITLE
Published gem should be sync with the last master

### ISSUE THREAD

**Issue by dej611** [lingz/alphabetical_paginate#30]
Several pull requests have been merged recently in `master` but the published gem is still pointing to a pretty old version.

* [x] Retest `master`
* [x] Bump version to 2.3.0
* [x] Publish gem

**Comment by dej611** [comment]
#31 should fix the issue with some more stuff.

Perhaps it should be implemented in a better way but I didn't have much time.

**Comment by nlevchuk** [comment]
@lingz please publish the gem at rubygems (2.2.4).

**Comment by lingz** [comment]
I'll be back from traveling in about three days so will release. Sorry for
the delay!

**Comment by nlevchuk** [comment]
@lingz good news! :+1: I look forward to a new release

**Comment by nlevchuk** [comment]
@lingz Hi. When are you going to release? Or if you have any questions about my changes (pull request) let me know. Thanks

**Comment by lingz** [comment]
Released. Very sorry for the delay!

**Comment by nlevchuk** [comment]
@lingz Thanks :+1:
