### ISSUE TITLE
Custom letters count in availableLetters variable

### ISSUE THREAD

**Issue by Samhane** [lingz/alphabetical_paginate#33]
Hello, is there way to make pagination with 'Av' or 'Ava' ? 
I want to set count of letters to 2, or 3, depending on count rows in db

**Comment by dej611** [comment]
What's the aim of this?

If you increase the number of letters for each alphabet character to 3 you may end up with at thousands of buttons potentially. 

Looking at the code it shouldn't be hard already (not in DB mode) to use it.

**Comment by lingz** [comment]
I agree with @dej611 the resolution would be too high for normal usage. It is a very simple modification if you want to do it though.
