### ISSUE TITLE
It shouldn't show any pagination bar when no data is available

### ISSUE THREAD

**Issue by dej611** [lingz/alphabetical_paginate#34]
As in will_paginate, the pagination bar should be hidden when there's no data to paginate I think.

Seeing the following makes me assume that there's something else in a different letter:
![screen shot 2015-02-22 at 18 30 12](https://cloud.githubusercontent.com/assets/924948/6319762/008c3a72-bac1-11e4-91d5-5a8f0e63ddb7.png)

While I see that this may have an impact on performances, it may prevent the user to try to attempt random clicks while browsing.

In will_paginate it just doesn't render the pagination bar when no data it's available:
![screen shot 2015-02-22 at 18 30 25](https://cloud.githubusercontent.com/assets/924948/6319767/2638fbac-bac1-11e4-8108-363c8ea270b6.png)

**Comment by dej611** [comment]
Made it work with the #35 pull request.

**Comment by lingz** [comment]
Already merged and released in 2.3.0
