### ISSUE TITLE
Support cyrilic and english later in conjunction

### ISSUE THREAD

**Issue by bkmz** [lingz/alphabetical_paginate#40]
The gem has support for the Russian language, but it is available when you switch the locale of the application. But you have not considered an option when the data for pagination, regardless of the application language can be in Russian and in English? For example a list of user names, or a list of surnames.

Sorry for my English, I do not know him very well

**Comment by nlevchuk** [comment]
@bkmz i think we had no need to do so. If you want just create pull request

**Comment by grishinoleg** [comment]
The thing is that usually you would not mix languages like that. If your website is in Russian, you should not write Jonson next to Иванов, but write Джонсон instead. Just my opinion. Submit a PR if you still need this functionality.

In Russian:
Обычно, если твой сайт на русском, то не надо писать Johnson рядом с Иванов, а переводить всё и писать Джонсон. ИМХО. Отправь pull request, если тебе всё таки нужна эта функциональность.
